server:
  port: 9091 
  
spring:
  application:
    name: GREET-API 
  boot:
    admin:
      client:
        url: http://localhost:1111
        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: '*'